version: '3'
services:
  locki_backend:
    build: ./api
    container_name: locki_backend
    environment:
      - PYTHONUNBUFFERED=True
      - API_SECRET=hqyHwsyFwpsuhajhMJ8GaV4a10GWNsPQrx5eenjgCPNq
      - API_HOST=127.0.0.1
      - API_PORT=5000
      - API_DEBUG=1

      - PG_HOST=db_locki:5432
      - PG_USER=postgres
      - PG_PASS=postgres
      - DB_NAME=postgres

    restart: on-failure
    volumes:
      - ./api:/api/api
    depends_on:
      - db_locki
    ports:
      - "5000:5000"
    command: gunicorn -b 0.0.0.0:5000 -w 4 api_runner:app --reload
  db_locki:
      container_name: db_locki
      image: postgres:12
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_DB=postgres
      volumes:
        - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: { }